import Head from "next/head";
import styles from "../styles/Home.module.scss";
import User from "./user";
import UserItem from "./user/[id]";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <User />
        
        
      </main>

      <footer className={styles.footer}>Ayın Personeli Listesi</footer>
    </div>
  );
}
export default Home;
